# Generated by Django 5.1.4 on 2025-01-02 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_acess', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=2)),
                ('codigo_ibge', models.CharField(max_length=7)),
                ('pais', models.CharField(max_length=50)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_modificacao', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='entidade',
            name='tipo',
            field=models.CharField(choices=[('P', 'Prefeitura'), ('C', 'Câmara'), ('RPPS', 'RPPS'), ('SAAE', 'SAAE'), ('O', 'Outros')], max_length=4),
        ),
    ]
