# Generated by Django 5.1.4 on 2025-01-02 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_acess', '0002_cidade_alter_entidade_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entidade',
            name='cidade',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='control_acess.cidade'),
        ),
    ]
