# Generated by Django 5.1.4 on 2025-01-02 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control_acess', '0003_alter_entidade_cidade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entidade',
            name='estado',
        ),
    ]
