# Generated by Django 5.1.4 on 2025-01-02 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_acess', '0005_remove_entidade_pais'),
    ]

    operations = [
        migrations.CreateModel(
            name='config_acesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('tp_conexao', models.IntegerField(choices=[(1, 'TeamViewer'), (2, 'AnyDesk'), (3, 'QSConect')])),
                ('id_conexao', models.CharField(max_length=100)),
                ('senha_conexao', models.CharField(max_length=100)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_modificacao', models.DateTimeField(auto_now=True)),
                ('entidade', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='control_acess.entidade')),
            ],
        ),
        migrations.CreateModel(
            name='log_acesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tp_conexao', models.CharField(max_length=100)),
                ('data_acesso', models.DateTimeField(auto_now=True)),
                ('ip_acesso', models.GenericIPAddressField()),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_modificacao', models.DateTimeField(auto_now=True)),
                ('entidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control_acess.entidade')),
            ],
        ),
    ]
