# Generated by Django 5.1.4 on 2025-01-02 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_acess', '0006_config_acesso_log_acesso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config_acesso',
            name='senha_conexao',
            field=models.CharField(max_length=200),
        ),
    ]
