# Generated by Django 5.1.4 on 2025-01-03 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_acess', '0007_alter_config_acesso_senha_conexao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config_acesso',
            name='entidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control_acess.entidade'),
        ),
        migrations.AlterField(
            model_name='config_acesso',
            name='id_conexao',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='entidade',
            name='cep',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='entidade',
            name='cidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control_acess.cidade'),
        ),
        migrations.AlterField(
            model_name='entidade',
            name='cnpj',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='entidade',
            name='data_modificacao',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='entidade',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='entidade',
            name='endereco',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='entidade',
            name='telefone',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
