# Generated by Django 5.1.4 on 2025-01-03 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_acess', '0008_alter_config_acesso_entidade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='log_acesso',
            name='user_acesso',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
